### ISSUE TITLE
Problème de chargement de la page des classes de LOINC

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#1]
http://stageportal.lirmm.fr/ontologies/LOINC/?p=classes
ne se cahrge pas ou affiche une erreur

Visiblement l'API fonctionne
http://data.stageportal.lirmm.fr/ontologies/LOINC/classes

**Comment by vemonet** [comment]
Le problème vient de l'ontologie : il n'y a pas de liens subClassOf entre les concepts. BioPortal utilise ces liens pour créer le "treeview" des classes
Les plus hauts concepts sont des subClassOf owl:Thing normalement et on les retrouve à cet endroit de l'API : 
http://data.stageportal.lirmm.fr/ontologies/LOINC/classes/roots

Note que recherche des termes de LOINC (exemple : Lutéotropine T07 après épreuve [Arbitraire/Volume] Sérum/Plasma ; Numérique ) marche dans le search et l'annotator
Le seul problème vient de l'affichage du treeview dans l'UI car aucune relation de subClassOf dans l'ontologie

**Comment by jonquet** [comment]
Mettre umls2015ab sur tubo pur que je puisse la regarder car visiblement il y a pas mal de problème.

**Comment by jonquet** [comment]
C'est un problème partiulier a LOINC. Normalement on devrait avoir une hierarchie, cf LOINC en ENG sur : https://bioportal.bioontology.org/ontologies/LOINC/?p=classes&conceptid=root

Faut inspecter la version UMLS et le résultat obtenu par UMLS2RDF pour voir pourquoi on a pas la hiérarchie.

**Comment by jonquet** [comment]
Bon je confirme que LNC-FR-FR dans UMLS 2015ab ne contient pas de hierarchie. 
En outre les labels sont vraiment horribles et ne servent a rien chez nous.
Je propsoe qu'on oublie cette ontologie pour le moment.
