### ISSUE TITLE
Activer les slices 

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#10]
Il s'agit d'activer les slices pour chacun des groupes que nous avons sur le SIFR BioPortal.
C'est a dire que comme pour AgroPortal, on garde une correlation slice/groupe.

**Comment by jonquet** [comment]
2 groupes concernés ajoutés recement: NCBOBP et LIMICS

**Comment by vemonet** [comment]
Ok, par contre actuellement il n'y a absolument aucune slice sur le SIFR BioPortal
Si je synchronise les slices avec les groupes on en aura 4 (LIMICS, CISMEF, NCBOBP, UMLS)

Je créé les 4 ou juste les 2 (NCBOBP et LIMICS) ?

**Comment by jonquet** [comment]
Créer les 4 slices, comme ca on garde une correspondance.
