### ISSUE TITLE
Fixer le probleme de soumission sur HRDO

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#11]
J'ai essayé de soumettre HRDO 
http://bioportal.bioontology.org/ontologies/HRDO/

avec comme pullLocation l'ontologie de NCBO BioPortal.
Et j'ai eu un probleme "something went wrong" au moment de la soumission.
Cela ressemble pas mal a #9 

J'ai ensuite essayé en mettant l'ontologie via le fichier téléchargé de chez NCBO et cela a pas marché non plus. Aie.

**Comment by jonquet** [comment]
Humm en fait je pense que la 2eme fois cela a marché... même si comme cela le fait  de temps en temps (quand l'ontologie est grosse);.. ca m'a affiché "went wrong"

Donc en fait, pour résumé: le bug a l'air d'etre quand on soumet une ontologies avec une pull location la premiere fois.

**Comment by vemonet** [comment]
Contrairement à TOP-MENELAS ( #9 ) ici le fichier de logs du parsing (parsing.log) n'est même pas créé. Bien que je retrouve le fichier hrdo.owl dans `/srv/ncbo/repository/HRDO/1/hrdo.owl`

Quand on lance le processing: "E, [2016-12-05T10:13:35.151367 #3435] ERROR -- : Error, cannot find latest submission."
Le problème est que la submission n'a pas été créée.

Je vais faire quelques tests

**Comment by vemonet** [comment]
J'ai trouvé le problème, je confirme sa résolution après midi

**Comment by jonquet** [comment]
Je ferme celui la car le problème est réglé.
