### ISSUE TITLE
Modification de la page d'acceuil et de l'UI

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#12]
Faire les mêmes chgt que décrits dans: 
https://github.com/agroportal/agroportal_web_ui/issues/59

- Onglet info
- Page Help (=> publi JFIM)
- News
- Links (y inclus le lien a la page web du projet SIFR)
etc.

**Comment by jonquet** [comment]
Sur le SIFR BP, enlever le "Search resources" bloc

Edit Vincent : c'est fait

**Comment by jonquet** [comment]
Modifier le texte en chgt BioPortal par "SIFR BioPortal"
"Use the SIFR BioPortal to access and share French biomedical ontologies and terminologies."

Edit Vincent: c'est fait

**Comment by amineabdaoui** [comment]
@jonquet @vemonet 
J'avais également noté que le message d'erreur du sifr bioportal lorsque l'apikey n'est pas donnée renvoie au bioportal original.
"Your API Key can be obtained by logging in at http://bioportal.bioontology.org/account"

Il serait peut etre mieux de renvoyer l'utilisateur du sifr bioportal à l'adresse http://bioportal.lirmm.fr pour obtenir la bonne api key.

Edit Vincent: c'est fait

**Comment by vemonet** [comment]
Quelles news on peut mettre ?

**Comment by jonquet** [comment]
Pour les links... faut faire un truc rapide un peu comme le bas de la nouvelle UI du NCBO  BioPortal. 
Pour les news, laissons tomber... faisons plutôt le lecteur de feed twitter qui affichera que les Tweets d'un certain compte (et de ceux qui sont suivis par ce compte).  Je ferai un compte aussi pour le Sifr Bioportal.

**Comment by jonquet** [comment]
Vu la page sur le serveur de prod aujourd'hui. 

*** Pour la age d'accueil:
- Enlève news. On fera autrement... sinon ce sera statique a mourir.
- Met le bloc "slice" en haut a gauche, que TOUT rentre sur un écran si possible.
- Garde les icônes de liens. 
	Et envoie doc vers: https://github.com/sifrproject/bioportal_web_ui/wiki 
	Ajoute une icone pour SPARQL et envoie vers la page de test du Sparql endpoint

Il manque encore: 
- Page Help (=> publi JFIM)
- Pour la page about... pour le moment enlève tout et mets que le lien vers le projet SIFR et le papier JFIM.
- Le lien release notes: a changer vers les notres

SIFR: https://github.com/sifrproject/bioportal_web_ui/wiki/Release-notes
AGRO: https://github.com/agroportal/documentation/wiki/Release-notes

Pour SIFR
Sur la page d’accueil indique (sous links): 
"Les ontologies du SIFR BioPortal sont soit: 
- extraites en français de l’UMLS (quand une version française existe),
- récupérées automatiquement du NCBO BioPortal (vue française des ontologies multilingues), 
- chargées directement par les utilisateurs,
- fournies par CISMeF (www.chu-rouen.fr/cismef/), suite au développement d’un export OWL pour la plateforme HeTOP (http://www.hetop.eu/hetop/). Pour obtenir une ontologie ou terminologie au format OWL veuillez contacter CISMeF directement.
"

**Comment by vemonet** [comment]
Publi JFIM : https://hal.archives-ouvertes.fr/hal-00492022 ?

**Comment by jonquet** [comment]
Clement Jonquet, Amina Annane, Khedidja Bouarech, Vincent Emonet & Soumia Melzi. SIFR BioPortal : Un portail ouvert et générique d’ontologies et de terminologies biomédicales françaises au service de l’annotation sémantique, In 16th Journées Francophones d'Informatique Médicale, JFIM'16. Genève, Suisse, July 2016. pp. 16.

https://hal.archives-ouvertes.fr/hal-01398250v1
http://www.lirmm.fr/~jonquet/publications/documents/Article_JFIM2016_SIFR_Jonquet.pdf

**Comment by vemonet** [comment]
J'ai remplacé l'ancienne publication par la nouvelle JFIM

Et j'ai traduit les anciens textes de l'anglais vers le français dans Help pour que ce soit plus logique. j'ai garder la même construction qu'avant pour aller vite mais ça fait pas mal de répétitions d'un paragraphe à un autre
Anciennement :
```
Welcome to the National Center for Biomedical Ontology’s BioPortal. BioPortal is a Web-based application for accessing and sharing biomedical ontologies.
SIFR BioPortal allows users to browse, upload, download, search, comment on, and create mappings for ontologies.
Users can browse and explore individual ontologies by navigating either a tree structure or an animated graphical view. Users can also view mappings and ontology metadata, and download ontologies.
Additionally, users who are signed in may also submit a new ontology to the library. All submissions to the library are reviewed.
```
D'ailleurs ne serait-ce pas plus logique de traduire la plupart des petits textes d'explications ? Sur la homepage, etc

Est-il vraiment utile d'avoir une fenêtre about **et** une fenêtre help ?

**Comment by jonquet** [comment]
Non pas nécessairement. Si tout rentre dans une page, on peut en garder q'une. 

Sur Help: Attention pour Web services de bien inclure les différents liens qui viennent vers chez nous. 
Pour les refs, laisse bien la publi originale Noy etal 2009 et la notre Jonquet et al 2016. Il y a un 's après ontology. Dans announce list enlève l'email notification qui existe pas et remplace par sifrportal-support@lirmm.fr pour nous joindre et demander a être ajouté a sifrportal-users@lirmm.fr pour être joint.

De About: Garde que team. 

Tout cela changera avec la nouvelle UI du NCBO dans qq mois. Il nous faut juste pointer vers les ressources extérieures du portail pour le moment.

**Comment by jonquet** [comment]
Je ferme ce tracker par rapport a la release de cette semaine.
