### ISSUE TITLE
Changer l'appel REST generé automatiquement pour l'Annotator dans l'UI

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#13]
Pourrez tu changer l'appel REST par défaut généré dans l'UI des Annotators pour inclure les paramètres:
&display_links=false
&display_context=false

C'est bien plus pratique quand on veut voir les résultats et les montrer.

D'ailleurs ce line pourrait etre transformer en vrai lien URL comme ca il n'y a qu'a cliquer... si il faut une apikey on peut encoder celle de l'utilisateur "demo";.. ou en crée une specialement pour l'UI.

Au cas ou ce soit approprié: a terme on va venir inserer dans l'UI des liens vers l'API assez souvent. Je trouve que le lien UI/API n'est pas assez present dans la palteforme...

**Comment by jonquet** [comment]
Tester en prod aujourd'ui. Ok niquel le lien marche. 
Il resterait a faire 👍 
- &display_links=false&display_context=false
- remplacer le long lien par un jolie bouton qui se voit et appellé "Corresponding REST web service call"
- les liens "Format Results As: JSON RDF" ne marche plus.
- Faudrait ajouter les deux  formats aussi: BRAT et QUAERO (voir avec @twktheainur )

**Comment by vemonet** [comment]
* `&display_links=false&display_context=false` fait
* Joli bouton : fait

**Comment by vemonet** [comment]
* les liens "Format Results As: JSON RDF" ne marchent plus.
Ils marchaient mais petit bug quand présence de single quote ( ' ), bug également présent chez le NCBO.

J'ai corrigé ça (également corrigé pour le NCBO, et fait une petit pull request)

Il ne reste plus qu'à voir BRAT et QUAERO avec Andon

**Comment by jonquet** [comment]
C'est simple: format=brat
                     format=quaero

C'est déployé ou ?

**Comment by twktheainur** [comment]
Effectivement format=brat ou format=quaero 
Par contre, il y a aussi des variantes pour quero, par quaeroimg (on supprimes les groupes sémantiques ambigus) et quaerosg (si il y a plusieurs groupes sémantiques, on prends le premier, ce qui est aléatoire), mais ça c'est plus pour les expériences d'évaluation, je pense qu'on peut ne pas mettre ceux là dans l'interface 

Andon
