### ISSUE TITLE
Modification de la page "Edit Ontology Information"

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#14]
Dans le cadre "Viewing restrictions" ajouter: 
- Public ontologies will be accessible to everyone via UI and API. Download can be desactivated on demand.
- Private ontologies are only accessible via UI and API to logged users listed explicitley.

A completer.

**Comment by jonquet** [comment]
Small UI change

**Comment by vemonet** [comment]
Fais dans un tooltip
