### ISSUE TITLE
Leading spaces and shifted annotation highlights in the Annotator interface 

### ISSUE THREAD

**Issue by twktheainur** [sifrproject/bioportal_web_ui#15]
Spaces and newlines in the annotator text field before the actual text cause the annotation offsets shown in the results to be shifted by the number of spaces and newlines. 

I managed to reproduce the problem on stageportal.lirmm.fr, bioportal.lirmm.fr and upstream on bioportal.bioontology.org.

<img width="1916" alt="screen shot 2017-03-02 at 19 32 52" src="https://cloud.githubusercontent.com/assets/82064/23521392/107229d8-ff7f-11e6-9017-42c7a14e1f95.png">

**Comment by jonquet** [comment]
Not addressed for the moment. Small enhancement CC @mdorf  for information as it also happen on the NCBO Annotator.

**Comment by jonquet** [comment]
Transfer to new repo.
