### ISSUE TITLE
Page Annotator

### ISSUE THREAD

**Issue by amineabdaoui** [sifrproject/bioportal_web_ui#16]
Quelques retours sur la page http://stageportal.lirmm.fr/annotator/

1. Deux fois le mot SIFR dans la description: "The Stage SIFR SIFR BioPortal Annotator processes text".
2. Le bouton "insert sample text" met un example de texte en anglais alors qu'on va utiliser des ontologies/terminologies françaises.
3. Les types sémantiques sont en français alors que tout le reste est en anglais (groupes sémantiques, ontologies..).

**Comment by jonquet** [comment]
1. et 2. a changer
3. Les ontologies ont des noms en français sur le SIFR BioPortal. Par contre effectivement il faut traduire les groupes sémantiques n Fr pour le SIFR BioPortal et garder les eng pour AgroPortal  avec ces valeurs

ACTI	Activités & Comportements
ANAT	Anatomie
CHEM	Produits chimiques & Médicaments
CONC	Concepts & Idées
DEVI	Dispositifs
DISO	Maladies
GENE	Gènes et Séquences moléculaires
GEOG	Zone géographiques
LIVB	Êtres vivants
OBJC	Objets
OCCU	Profession
ORGA	Organisations
PHEN	Phénomène
PHYS	Physiologie
PROC	Procédure

**Comment by twktheainur** [comment]
3 est corrigé sur les branches sifr et sifr_annotatorplus, pas sur lirmm car c'est commun avec agroportal, idem pour 2 (juste sur SIFR annotator, pas sur annotator plus bien entendu).

**Comment by jonquet** [comment]
@vemonet Tu pourrais regarder 1 et 2 .

Ensuite, 
J'ai testé 2-3 fois ce matin lors de la réunion PractickPharma. C'est pas encore stable:
- une fois cela n'a pas marché du tout chez moi tout en marchant chez Adrien (j'ai l'impression qu’après un call on a parfois un problème)
- désormais... il y a plus rien de détecter par Context pour la phrase : "Le patient ne montre aucun signe de fièvre. Son père a déjà eu de l’arthrose. Il a des antécédents de dépression."
- sur Firefox, j'ai fait un test avec Context et "Fièvre" et seulement la première colonne de Context affiche des résultats.

**Comment by amineabdaoui** [comment]
@jonquet j'ai un programme qui lance des requêtes en continu sur stageportal pour construire mon corpus d'éval de ConText. Peut etre que c'est à cause de la...
Ps. Il lui reste encore env 12-15 heures.

**Comment by twktheainur** [comment]
@jonquet @amineabdaoui Après la fin des requêtes d'amine, tout remarche comme il faut, mais il y a manifestement un problème d'accès concurrent et de montée en charge. Je vais faire des modifs au niveau du proxy pour que ce soit mieux géré

**Comment by jonquet** [comment]
- Virer la ligne "Subscribe to"
- Lien pour Semantic group vers https://semanticnetwork.nlm.nih.gov/
- Transformer la ligne URL générée en bouton clickable

**Comment by vemonet** [comment]
C'est fait, en général j'ai remplacé les URL des "Format results as" en boutons également
