### ISSUE TITLE
Mettre a jour de UMLS 2016ab

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#17]
MSHFRE, MDRFRE
Et exporter LOINC-FR-FR (la mettre dans le repertoire sur le Gdrive pour bosser dessus)

**Comment by vemonet** [comment]
https://drive.google.com/drive/folders/0B7_VpShsghfQcHpYQ1lQdXUwSHM

Still need to upload it on bioportal.lirmm.fr

**Comment by vemonet** [comment]
MDRFRE and MSHFRE uploaded on bioportal.lirmm.fr
