### ISSUE TITLE
Bug avec une URI de MeSH

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#18]
http://bioportal.lirmm.fr/ontologies/MSHFRE?p=classes&conceptid=http%3A%2F%2Fpurl.lirmm.fr%2Fontology%2FMSHFRE%2FD001835

"Poids du corps"

est trouvé par l'annotator mais ne s'ouvre pas dans la navigation des classes

**Comment by vemonet** [comment]
Pas de problèmes apparemment.
