### ISSUE TITLE
Mettre MTHMSTFRE et CIM-10 dans SIFR BioPortal

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#2]
Apres revue et discussions, même si elles ne sont pas parfaites, on va les mettre.

**Comment by vemonet** [comment]
Problème avec l'ontologie MTHMSTFRE : il n'y a pas de liens subClassOf entre les concepts (même problème que pour LOINC). BioPortal utilise ces liens pour créer le "treeview" des classes (LOINC et MTHMSTFRE : réunir les 2 problèmes dans une seule issue ?)

**Comment by jonquet** [comment]
Normalement cela ne doit pas empecher l'onglet classe de se charger sans rien afficher dans l'emplacement de l'arbre. C'est ce qui se passe par exmemple pour MTHMSTFRE coté BioPortal :
https://bioportal.bioontology.org/ontologies/MSTDE-FRE/?p=classes&conceptid=root

**Comment by jonquet** [comment]
A ne pas mixer avec l'autre issue.
C'est un problème partiulier a LOINC. Normalement on devrait avoir une hierarchie, cf LOINC en ENG sur : https://bioportal.bioontology.org/ontologies/LOINC/?p=classes&conceptid=root

Faut inspecter la version UMLS et le résultat obtenu par UMLS2RDF pour voir pourquoi on a pas la hiérarchie.

**Comment by vemonet** [comment]
En fait un workaround a été ajouté pour contourner ce problème avec les ontologies sans relation de subClassOf : il est possible de préciser qu'une ontologie est "flat" (dans ce cas l'UI n'essaiera pas de créer le treeview)
http://data.bioontology.org/ontologies/MSTDE-FRE?display=all
On peut voir que flat = true (vérifié sur la VM)

**Comment by jonquet** [comment]
Oui mais ce n'st pas le cas pour LOINC, voir sur le NCBO BioPortal: elle a une hierachie.  Je regarde sur UMLS ce que cela dit.

**Comment by jonquet** [comment]
Je ferme ce tracker comme MTHMSTFRE et CIM-10 sont dans SIFR BioPortal desormais et qu'ils fonctionnenent. 
J'ouvrirai autre chose pour LOINC.
