### ISSUE TITLE
Modify UI to handle new scoring threshold parameters

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#21]
This is the UI change for https://github.com/sifrproject/annotators/issues/25 

Currently tested on stage server

**Comment by jonquet** [comment]
Couple of comments: 

This will be the moment to add "?" comments on the 4 bottom parameters. I suggest: 
- "Include Ancestors Up To Level" Renamed to "Ancestor Level" and comment "Specifies the level in the ancestor hierarchy up to which the direct annotations will be expanded to."
- Include Score => "Score the annotations following the previous 2009 NCBO measure (old) or the C-Value measure (cvalue). If hierarchy expansion is also used then prefer cvalueh. "
- Score Threshold => "Specifies the minimum score value for annotations."
- Confidence Threshold => "Specifies the minimum position in the scoring distribution (between 1 and 100)"

Peut etre pour le Confidence threshold le pop up devrait expliciter la limite entre 0 et 100.

**Comment by twktheainur** [comment]
@jonquet Issues with the parameter handling all fixed. Help icons added, please test on the stageportal UI

**Comment by jonquet** [comment]
UI is ok on stage.
One small remark: if one of the score field is empty (no 0 or nothing) then an error occur. No big deal, at the API level the bug is not here and the default parameter is used. 

On SIFR BP, the UI is not the latest branch.

**Comment by jonquet** [comment]
Has been implemented.
