### ISSUE TITLE
Uploader les mappings multilangues d'Amina en production

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#3]
En cours.
Restera MTHMSTFRE et CIM-10 une fois que les ontologies seront dedans

**Comment by vemonet** [comment]
CIM-10 fait

**Comment by jonquet** [comment]
Je vois que MTHMSTFRE aussi.
J'ai fait les comparaisons des stats dans SIFR BioPOrtal  et la soumissions WIMS d'Amina, il semblerait qu'il y ait des gros bug juste pour :
- MEDLINEPLUS (on a 1520 mappings au lieu de 771
- CISP2 (on 5063 mappings au lieu de 665)

Je vais lui assigner le tracker pour qu'elle regarde

**Comment by jonquet** [comment]
Non en fait on est bon j'avais pas fait attention que pour ces ontologies la on a plus de mappings. C'est normal.
