### ISSUE TITLE
Recent mapping call is too long and prevent the welcome page from loading

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#5]
This bug occurs sincce we hqve uploqd the thoishand of mapiings from Amina. The call 
http://data.bioportal.lirmm.fr/mappings/recent

The call is too long and prevent the welcome page from loading vbecause it does go over all the mappings in the triple store to see the recent ones.

**Comment by vemonet** [comment]
The problem comes from `ontologies_linked_data/lib/ontologies_linked_data/mappings/mapping.rb` in `self.recent_rest_mappings`
The following SPARQL query take too much time:

```
SELECT DISTINCT ?s
FROM <http://data.bioontology.org/metadata/MappingProcess>
WHERE { ?s <http://data.bioontology.org/metadata/date> ?o }
ORDER BY DESC(?o) LIMIT 5
```

It needs to order all mappings

Solution: recent mappings really cached (a cache that would be updated when a recent mapping is added, instead of querying on the fly)

**Comment by jonquet** [comment]
Thanks Vincent for the details. I am sharing this with the NCBO team. I have already mentionned the problem. @mdorf

A clean solution will be to maintain somewhere a simple data structure that will contain only the 5 latests mappings and that will be updated each time a new mapping is added to BioPortal. Then mappings/recent/ service will not event go to the triple store anymore but only to that structure.
Such data structure can be populated at BioPortal start using the triplestore query only once.

What do you think?

**Comment by vemonet** [comment]
A params $DISPLAY_RECENT has been added in bioportal_config_production.rb to be able to unactivate it. If we want to put back the feature we will need to create an entry in redis
