### ISSUE TITLE
Bloquer le telechargement pour les ontologies suivantes

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#7]
Pour lesquelles nous n'avons pas encore d'autorisation formelle: 
MDRFRE
WHO-ARTFRE
MSHFRE
CIM-10

Il faudrait juste désactiver le lien de téléchargement. Je les débloquerai ensuite plus ou moins un par un.

**Comment by vemonet** [comment]
How to do it: https://github.com/ncbo/bioportal_web_ui/commit/1801c88bd0c36944c10a07f997fd5f12cb9db302

**Comment by vemonet** [comment]
Done. Now we can restrict ontologies directly from the bioportal_config file. See https://github.com/sifrproject/bioportal_web_ui/commit/af322f549b4859d9cd4d5912023994b3e79b5eea

**Comment by jonquet** [comment]
Je reouvre ca car je vois MDRFRE en download encore sur le SIFR BP.

**Comment by jonquet** [comment]
Fermé suite au passage en prod du 15/02

**Comment by jonquet** [comment]
@vemonet tu peux faire aussi FRNORM svp.

**Comment by vemonet** [comment]
Le fait qu'elle soit en private ne suffit pas ?

**Comment by vemonet** [comment]
C'est fait
