### ISSUE TITLE
Dereferencemebt des URI de MUEVO

### ISSUE THREAD

**Issue by jonquet** [sifrproject/bioportal_web_ui#8]
Il semblerait qu'on ait un problème de dereferencement des URI de MUEVO.

Par exemple: http://purl.lirmm.fr/ontology/MuEVo/vpm61

Se dereference vers: http://bioportal.lirmm.fr/ontologies/MUEVO?p=classes&conceptid=vpm61 
qui ne marche pas.

Celle qui marche est: 
http://bioportal.lirmm.fr/ontologies/MUEVO/?p=classes&conceptid=http%3A%2F%2Fpurl.lirmm.fr%2Fontology%2FMuEVo%2Fvpm61

Ceci n'est pas le cas pour Medra par esxmple qui marche bien: 
http://purl.lirmm.fr/ontology/MDRFRE/10007541  =>
http://bioportal.lirmm.fr/ontologies/MDRFRE?p=classes&conceptid=10007541

Est-ce que cela ne viendrait pas de la casse dans le nom de l'ontologie dans l'URI ?

**Comment by vemonet** [comment]
Je l'ai mis à jour pour qu'il utilise directement l'URI du concept (plus sûr).
Mais le problème avec MUEVO c'est que son acronym est tout en majuscule (MUEVO) mais que l'acronym utilisé pour générer les conceptid est différent : MuEVo

Quand je reçois http://purl.lirmm.fr/ontology/MuEVo/vpm61 je ne peux pas deviner que c'est dans MUEVO que je dois chercher et non pas MuEVo (et je peux pas tout mettre en majuscule car les minuscules sont possibles et c'est sensible à la casse)

**Comment by vemonet** [comment]
http://bioportal.lirmm.fr/ontologies/MUEVO?p=classes&conceptid=http%3A%2F%2Fpurl.lirmm.fr%2Fontology%2FMuEVo%2Fvpm61
marche par exemple

**Comment by jonquet** [comment]
OK fichier Muevo a changer
